use anyhow::{anyhow, Result};
use clap::Parser;
use hex;
use raiko_core::{
    interfaces::ProofRequest,
    provider::rpc::RpcBlockDataProvider,
    Raiko,
};
use raiko_lib::{
    builder::calculate_block_header,
    consts::SupportedChainSpecs,
    input::GuestInput,
    primitives::{Address, B256},
    proof_type::ProofType,
    protocol_instance::ProtocolInstance,
};
use serde::{Deserialize, Serialize};
use std::io::{self, Read};

mod proof;
mod quote;
mod signature;

use proof::parse_proof_bytes;
use quote::QuoteInfo;

#[derive(Parser, Clone)]
#[command(name = "sgx-verifier")]
#[command(about = "Verify SGX proofs generated by Raiko", long_about = None)]
struct Args {
    /// Path to JSON file containing the proof (if not provided, reads from stdin)
    #[arg(short, long)]
    file: Option<String>,
    
    /// Path to JSON file containing GuestInput for full verification (optional)
    #[arg(long)]
    guest_input: Option<String>,
    
    /// Generate GuestInput via RPC for full verification (requires --network, --block-number, etc.)
    #[arg(long)]
    generate_guest_input: bool,
    
    /// Network name (e.g., devnet, taiko_a7, taiko_mainnet)
    #[arg(long)]
    network: Option<String>,
    
    /// Block number to generate GuestInput for
    #[arg(long)]
    block_number: Option<u64>,
    
    /// L1 network name (e.g., ethereum, holesky, devnet)
    #[arg(long)]
    l1_network: Option<String>,
    
    /// Prover address (default: 0x70997970C51812dc3A010C7d01b50e0d17dc79C8)
    #[arg(long)]
    prover: Option<String>,
    
    /// Graffiti (default: 8008500000000000000000000000000000000000000000000000000000000000)
    #[arg(long)]
    graffiti: Option<String>,
    
    /// RPC URL for the network (if not provided, uses default from chain spec)
    #[arg(long)]
    rpc_url: Option<String>,
}

#[derive(Debug, Serialize, Deserialize)]
struct SgxProofJson {
    /// Proof bytes in hex format (0x prefix optional)
    proof: String,
    /// SGX Quote in hex format
    quote: String,
    /// Public key in hex format
    #[serde(default)]
    public_key: Option<String>,
    /// Instance address
    #[serde(default)]
    instance_address: Option<String>,
    /// Protocol instance hash (input hash)
    input: String,
}

#[derive(Debug, Serialize)]
struct VerificationResult {
    valid: bool,
    errors: Vec<String>,
    warnings: Vec<String>,
    proof_info: Option<ProofInfo>,
    quote_info: Option<QuoteInfo>,
}

#[derive(Debug, Serialize)]
struct ProofInfo {
    proof_type: String,
    instance_id: u32,
    new_instance_address: Address,
    input_hash: B256,
}

#[tokio::main]
async fn main() -> Result<()> {
    let args = Args::parse();
    // Read proof from file or stdin
    let json_content = if let Some(ref file_path) = args.file {
        std::fs::read_to_string(file_path)
            .map_err(|e| anyhow!("Failed to read file {}: {}", file_path, e))?
    } else {
        let mut buffer = String::new();
        io::stdin()
            .read_to_string(&mut buffer)
            .map_err(|e| anyhow!("Failed to read from stdin: {}", e))?;
        buffer
    };

    // Parse JSON
    let proof_json: SgxProofJson = serde_json::from_str(&json_content)
        .map_err(|e| anyhow!("Failed to parse JSON: {}", e))?;

    // Load or generate GuestInput
    let guest_input: Option<GuestInput> = if args.generate_guest_input {
        // Generate GuestInput via RPC
        let block_number = args.block_number
            .ok_or_else(|| anyhow!("--block-number is required when using --generate-guest-input"))?;
        eprintln!("Generating GuestInput via RPC for block {} on network {}...", block_number, args.network.as_ref().unwrap_or(&"unknown".to_string()));
        let guest_input = generate_guest_input_via_rpc(&args, block_number).await?;
        eprintln!("GuestInput generated successfully");
        Some(guest_input)
    } else if let Some(guest_input_path) = args.guest_input {
        // Load from file
        eprintln!("Loading GuestInput from file: {}", guest_input_path);
        let guest_input_content = std::fs::read_to_string(&guest_input_path)
            .map_err(|e| anyhow!("Failed to read guest input file {}: {}", guest_input_path, e))?;
        Some(serde_json::from_str(&guest_input_content)
            .map_err(|e| anyhow!("Failed to parse guest input JSON: {}", e))?)
    } else {
        None
    };

    // Verify the proof
    let result = verify_sgx_proof(&proof_json, guest_input.as_ref())?;

    // Output result as JSON
    let output = serde_json::to_string_pretty(&result)?;
    println!("{}", output);

    // Exit with error code if verification failed
    if !result.valid {
        std::process::exit(1);
    }

    Ok(())
}

fn verify_sgx_proof(proof_json: &SgxProofJson, guest_input: Option<&GuestInput>) -> Result<VerificationResult> {
    let mut errors = Vec::new();
    let mut warnings = Vec::new();

    // Parse proof bytes
    let proof_bytes = hex::decode(proof_json.proof.strip_prefix("0x").unwrap_or(&proof_json.proof))
        .map_err(|e| anyhow!("Failed to decode proof hex: {}", e))?;

    let proof = match parse_proof_bytes(&proof_bytes) {
        Ok(p) => p,
        Err(e) => {
            errors.push(format!("Failed to parse proof bytes: {}", e));
            return Ok(VerificationResult {
                valid: false,
                errors,
                warnings,
                proof_info: None,
                quote_info: None,
            });
        }
    };

    // Check if this is an aggregation proof (109 bytes) - skip instance hash verification for aggregation proofs
    let is_aggregation_proof = proof_bytes.len() == 109;

    // Parse input hash
    let input_hash = hex::decode(proof_json.input.strip_prefix("0x").unwrap_or(&proof_json.input))
        .map_err(|e| anyhow!("Failed to decode input hash: {}", e))?;
    if input_hash.len() != 32 {
        errors.push(format!("Invalid input hash length: expected 32 bytes, got {}", input_hash.len()));
    }
    let input_hash = B256::from_slice(&input_hash);

    // If GuestInput is provided, verify that the instance_hash matches
    // Skip instance hash verification for aggregation proofs (they use aggregation hash, not block instance hash)
    if let Some(guest_input) = guest_input {
        if is_aggregation_proof {
            warnings.push(
                "Aggregation proof detected. Skipping instance hash verification. "
                .to_string() +
                "Aggregation proofs use aggregation hash, not individual block instance hash."
            );
        } else {
            match verify_instance_hash(guest_input, &proof.new_instance_address, &input_hash) {
                Ok(()) => {
                    // Instance hash matches, this is good
                }
                Err(e) => {
                    // Try to get L1 inclusion block number from GuestInput for better error message
                    let l1_info = if guest_input.chain_spec.is_taiko() {
                        format!("L1 inclusion block: {}", guest_input.taiko.l1_header.number)
                    } else {
                        "".to_string()
                    };
                    
                    // For one-shot proofs, instance hash mismatch could be due to:
                    // 1. Different l1_inclusion_block_number (auto-detected may differ)
                    // 2. Different prover/graffiti parameters
                    // 3. Different block data or chain state
                    // Since signature and quote verification still validate the proof's cryptographic integrity,
                    // we treat this as a warning rather than an error.
                    warnings.push(format!(
                        "Instance hash verification failed: calculated hash does not match proof input hash. {}",
                        e
                    ));
                    if !l1_info.is_empty() {
                        warnings.push(l1_info);
                    }
                    warnings.push(
                        "This may be due to different l1_inclusion_block_number or other parameters. "
                        .to_string() +
                        "Signature and quote verification are still performed."
                    );
                }
            }
        }
    } else {
        warnings.push(
            "GuestInput not provided. Skipping instance hash verification. "
            .to_string() +
            "For full verification, provide GuestInput using --guest-input flag."
        );
    }

    // Verify signature (for one-shot proof, signature should match new_instance_address)
    match signature::recover_signer(&proof.signature, &input_hash) {
        Ok(recovered_address) => {
            if recovered_address != proof.new_instance_address {
                errors.push(format!(
                    "Signature verification failed: recovered address {} does not match expected signer {}",
                    recovered_address, proof.new_instance_address
                ));
            }
        }
        Err(e) => {
            errors.push(format!("Failed to recover signer from signature: {}", e));
        }
    }

    // Verify instance address matches if provided (only if not empty)
    if let Some(ref expected_addr) = proof_json.instance_address {
        if !expected_addr.is_empty() {
            let addr_hex = expected_addr.strip_prefix("0x").unwrap_or(expected_addr);
            let addr_bytes = hex::decode(addr_hex)
                .map_err(|e| anyhow!("Failed to decode instance_address: {}", e))?;
            if addr_bytes.len() != 20 {
                errors.push(format!("Invalid instance_address length: expected 20 bytes, got {}", addr_bytes.len()));
            } else {
                let expected = Address::from_slice(&addr_bytes);
                if expected != proof.new_instance_address {
                    errors.push(format!(
                        "Instance address mismatch: expected {}, got {}",
                        expected, proof.new_instance_address
                    ));
                }
            }
        }
    }

    // Parse and verify quote
    let quote_bytes = hex::decode(proof_json.quote.strip_prefix("0x").unwrap_or(&proof_json.quote))
        .map_err(|e| anyhow!("Failed to decode quote hex: {}", e))?;

    let quote_info = match quote::parse_quote(&quote_bytes) {
        Ok(info) => {
            // Verify REPORTDATA contains instance address
            if let Some(report_data_addr) = info.report_data_address {
                if report_data_addr != proof.new_instance_address {
                    warnings.push(format!(
                        "Quote REPORTDATA address {} does not match proof new instance address {}",
                        report_data_addr, proof.new_instance_address
                    ));
                }
            }
            Some(info)
        }
        Err(e) => {
            warnings.push(format!("Failed to parse quote (continuing anyway): {}", e));
            None
        }
    };

    let valid = errors.is_empty();

    Ok(VerificationResult {
        valid,
        errors,
        warnings,
        proof_info: Some(ProofInfo {
            proof_type: "one-shot".to_string(),
            instance_id: proof.instance_id,
            new_instance_address: proof.new_instance_address,
            input_hash,
        }),
        quote_info,
    })
}

/// Verify that the instance_hash calculated from GuestInput matches the provided input_hash
fn verify_instance_hash(
    guest_input: &GuestInput,
    instance_address: &Address,
    expected_hash: &B256,
) -> Result<()> {
    // Calculate block header from guest input
    let header = calculate_block_header(guest_input);
    
    // Build ProtocolInstance
    let pi = ProtocolInstance::new(guest_input, &header, ProofType::Sgx)
        .map_err(|e| anyhow!("Failed to create ProtocolInstance: {}", e))?
        .sgx_instance(*instance_address);
    
    // Calculate instance hash
    let calculated_hash = pi.instance_hash();
    
    if calculated_hash != *expected_hash {
        return Err(anyhow!(
            "Instance hash mismatch: calculated {} but proof has {}",
            calculated_hash,
            expected_hash
        ));
    }
    
    Ok(())
}

/// Generate GuestInput via RPC using the same code as Raiko
async fn generate_guest_input_via_rpc(args: &Args, block_number: u64) -> Result<GuestInput> {
    let network = args.network.as_ref()
        .ok_or_else(|| anyhow!("--network is required when using --generate-guest-input"))?;
    let l1_network = args.l1_network.as_ref()
        .ok_or_else(|| anyhow!("--l1-network is required when using --generate-guest-input"))?;
    
    let prover = args.prover.as_ref()
        .map(|s| s.parse::<Address>())
        .transpose()
        .map_err(|e| anyhow!("Invalid prover address: {}", e))?
        .unwrap_or_else(|| "0x70997970C51812dc3A010C7d01b50e0d17dc79C8".parse().unwrap());
    
    let graffiti = args.graffiti.as_ref()
        .map(|s| s.parse::<B256>())
        .transpose()
        .map_err(|e| anyhow!("Invalid graffiti: {}", e))?
        .unwrap_or_else(|| "8008500000000000000000000000000000000000000000000000000000000000".parse().unwrap());
    
    // Get chain specs
    let chain_specs = SupportedChainSpecs::default();
    let taiko_chain_spec = chain_specs.get_chain_spec(network)
        .ok_or_else(|| anyhow!("Unknown network: {}", network))?;
    let l1_chain_spec = chain_specs.get_chain_spec(l1_network)
        .ok_or_else(|| anyhow!("Unknown L1 network: {}", l1_network))?;
    
    // Override RPC URL if provided
    let mut taiko_chain_spec = taiko_chain_spec.clone();
    if let Some(rpc_url) = &args.rpc_url {
        taiko_chain_spec.rpc = rpc_url.clone();
    }
    
    // Create proof request
    let proof_request = ProofRequest {
        block_number,
        l1_inclusion_block_number: 0, // Will be determined from block data
        network: network.clone(),
        l1_network: l1_network.clone(),
        graffiti,
        prover,
        proof_type: ProofType::Sgx,
        blob_proof_type: raiko_lib::input::BlobProofType::ProofOfEquivalence,
        prover_args: Default::default(),
        batch_id: 0,
        l2_block_numbers: Vec::new(),
    };
    
    // Create Raiko instance
    let raiko = Raiko::new(
        l1_chain_spec.clone(),
        taiko_chain_spec.clone(),
        proof_request.clone(),
    );
    
    // Create RPC provider
    let provider = RpcBlockDataProvider::new(&taiko_chain_spec.rpc, block_number - 1)
        .await
        .map_err(|e| anyhow!("Failed to create RPC provider: {}", e))?;
    
    // Generate GuestInput
    // Note: l1_inclusion_block_number is set to 0, which means it will be automatically
    // determined from block data via traversal. This should match the behavior when the proof
    // was generated through the API.
    let guest_input = raiko.generate_input(provider)
        .await
        .map_err(|e| anyhow!("Failed to generate GuestInput: {}", e))?;
    
    // Log the actual L1 inclusion block number that was found
    if taiko_chain_spec.is_taiko() {
        let l1_inclusion_block = guest_input.taiko.l1_header.number;
        eprintln!("Found L1 inclusion block number: {}", l1_inclusion_block);
    }
    
    Ok(guest_input)
}

